version: '3.8'

services:
  pointly:
    build: .
    container_name: pointly-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pointly?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: application
      SPRING_DATASOURCE_PASSWORD: application
    networks:
      - pointly-network

  mysql:
    image: mysql:8.0
    container_name: pointly-mysql
    restart: always
    environment:
      MYSQL_DATABASE: pointly
      MYSQL_USER: application
      MYSQL_PASSWORD: application
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pointly-network

volumes:
  mysql-data:

networks:
  pointly-network:
    driver: bridge
